# Generated by Django 4.0.1 on 2022-01-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension_id', models.CharField(max_length=255, null=True)),
                ('mute_emails', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'extension_settings',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('content_type', models.CharField(max_length=255, null=True)),
                ('enc_item_key', models.TextField(null=True)),
                ('auth_hash', models.CharField(max_length=255, null=True)),
                ('user_uuid', models.CharField(max_length=255, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_user_agent', models.TextField(null=True)),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='NoteUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, null=True)),
                ('pw_func', models.CharField(max_length=255, null=True)),
                ('pw_alg', models.CharField(max_length=255, null=True)),
                ('pw_cost', models.IntegerField(null=True)),
                ('pw_key_size', models.IntegerField(null=True)),
                ('pw_nonce', models.CharField(max_length=255, null=True)),
                ('encrypted_password', models.CharField(max_length=255)),
                ('reated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pw_salt', models.CharField(max_length=255, null=True)),
                ('version', models.CharField(max_length=255, null=True)),
                ('updated_with_user_agent', models.TextField(null=True)),
                ('locked_until', models.DateTimeField(null=True)),
                ('num_failed_attempts', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
